version: "3.8"

services:
  app:
    build:
      context: .
    container_name: auth_service
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    env_file:
      - .env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]
